apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-clky
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-clky
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-clky
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-clky
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-clky
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-nejp-tenant/rhtap-demo-app/hacbs-test-project-clky@sha256:e0826fff399c870e35066547c7468368ac880b7f29f937c130a4202493942ebb
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
